---
env:
  browser: true
parserOptions:
  ecmaVersion: 2021
  sourceType: module
extends:
  - airbnb-base
rules:
  comma-dangle:
    - error
    - never
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - element
  no-useless-constructor: 0
  no-plusplus: 0
  max-len:
    - error
    - 120
  import/no-mutable-exports: 0
  import/prefer-default-export: 0
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - webpack.*.js
      - tools/**/*.js
overrides:
  - files: tools/**/*.js
    env:
      node: true
  - files: "webpack.*.js"
    settings:
      import/resolver: 'node'
  - files:
      - "*.ts"
    parser: "@typescript-eslint/parser"
    extends:
      - airbnb-base
      - plugin:import/typescript
      - plugin:@typescript-eslint/recommended
    rules:
      comma-dangle: 0
      import/no-extraneous-dependencies:
        - error
        - peerDependencies: true
      import/prefer-default-export: 0
      import/extensions: 0
      lines-between-class-members:
        - error
        - always
        - exceptAfterSingleLine: true
      max-len:
        - error
        - 120
      no-param-reassign:
        - error
        - props: true
          ignorePropertyModificationsFor:
            - element
      "@typescript-eslint/no-explicit-any": 1
    settings:
      import/resolver:
        webpack:
          config: 'webpack.dev.js'
  - files: "*.d.ts"
    parser: "@typescript-eslint/parser"
    extends:
      - airbnb-base
      - plugin:import/typescript
      - plugin:@typescript-eslint/recommended
    rules:
      import/no-extraneous-dependencies: 0
      import/prefer-default-export: 0
      max-len:
        - error
        - 120
      "@typescript-eslint/explicit-member-accessibility": 0
      "@typescript-eslint/no-explicit-any": 0
    settings:
      import/resolver:
        webpack:
          config: 'webpack.dev.js'
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
  import/extensions:
    - ".js"
    - ".ts"
