# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    tags:
      - 'v[0-9]*'  # This will trigger for tags starting with v followed by a number

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to determine the branch
      - name: Check if tag is on the main branch
        id: check-branch
        run: |
          BRANCH=$(git branch -r --contains ${{ github.ref }} | grep 'origin/main' || echo '')
          if [[ -n "$BRANCH" ]]; then
            echo "Tag is on the main branch"
            echo "is_main_branch=true" >> $GITHUB_OUTPUT
          else
            echo "Tag is not on the main branch"
            echo "is_main_branch=false" >> $GITHUB_OUTPUT
          fi
      - name: Upload artifact if that is on main branch
        if: steps.check-branch.outputs.is_main_branch == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
      - name: Deploy to GitHub Pages
        if: steps.check-branch.outputs.is_main_branch == 'true'
        id: deployment
        uses: actions/deploy-pages@v4
